@echo off
echo Pulling latest changes...
git pull origin main
echo Adding all changes...
git add .
echo Committing changes...
git commit -m "%1"
echo Pushing to remote...
git push origin main
echo Done!